src/trezor.js, src/trezor.test.js
This will allow the use of trezor with non-standard BIP32 paths.  The same check is performed but it has been downgraded to a warning.  This is a breaking change so versioning will need to be updated accordingly
=> allow unusual paths on trezor

src/hermit.js, src/hermit.test.js
Reading Hermit PubKey and XPub QR codes was broken.
Hermit key exporting QR codes have keys `bip32_path` and either `xpub` or `pubkey`. 
The `unchained-wallets` functions were expecting `bip32Path`.
To avoid any breaking changes, I simply renamed the field during the QR code data
parsing and validating.
=> fix(hermit): rename bip32_path to bip32Path during QR code parsing

package-lock.json, package.json, src/ledger.js
Due to a recent refactoring of the Ledger code, an old function accessible from the btc object itself is now split out into its own library because it does not require the transport or anything. Import these functions directly and refactor the call to the btc `app`.
Now the latest package versions work.
Ran through the test suite with Ledger and things are working. With U2F fallback (firefox) on MacOS, I get occasional fails to sign. Exit the btc app and re-open it, then try again. In my case, eventually it will sign. This is not a good experience, but it works. The webusb (Chromium) experience is vastly superior.
=> Refactor to update ledger deps to current

src/trezor.js
It's not a requirement to include the amounts with your inputs as the information is on chain. But if the caller does include it, include it.
=> Updates object to optionally include amount iff `amountSats` exists

src/ledger.js
Saw above while adding error messages, refactored a bit to change the method signature and also to remove duplicated bitcoinjs code and choosing rather to import from `unchained-bitcoin` and rebuild the unsigned transaction that way.
npm tests pass, I also ran through the device test suite with ledger nano S
=> Adds better error handling, refactor outputScript, add named params

src/trezor.js
requiredSigners could be <= pubkeys.length ... but the Trezor firmware seems to want to place signatures at the same index as the pubkey.
=> Set multisig signatures array size to length of pubkeys

src/ledger.js, src/ledger.test.js, src/trezor.js, src/trezor.test.js
If the signature ends in `0x01` and the downstream application is expecting a SIGHASH_ALL byte to be included, then this conditional will invalidate the signature.
Make this API always return the signature with the SIGHASH byte included.
=> Remove conditional logic to add SIGHASH_ALL byte

src/index.js, src/ledger.js, src/trezor.js
This PR adds an opt-in, completely optional way to interact with the Ledger and Trezor keystores in the event you would like them to return the root fingerprint of the device in addition to the `keyMaterial` (xpub or pubkey).
The old functionality remains untouched.
In the future, we will make a breaking change to these key export classes where the returned value is an Object instead of a string. But for now - we can still support both.
=> Adds optional `includeXFP` when exporting xpubs / public keys

src/index.js, src/trezor.js, src/trezor.test.js
When calling `ConfirmMultisigAddress` the user should expect this behavior:
For Device A which is in control of Public Key A at BIP32Path A:
1. The multisig address should be shown on the Device A.
2. BIP32Path A of the Public Key A is shown on Device A.
3. If Public Key A isn't in the redeem script of the multisig address, an error is thrown.
4. If the key on Device A at BIP32Path A isn't Public Key A, an error is thrown.
Before this PR, only 1-3 was true. This PR adds 4 via an optional parameter, for backwards compatibility.
`ConfirmMultisigAddress` currently only works on Trezor.  
The trezor interaction uses [getAddress](https://github.com/trezor/connect/blob/v8/docs/methods/getAddress.md#exporting-single-address). The important parameters passed to `getAddress` are: `path`, `address` …
=> Improve ConfirmMultisigAddress with optional publicKey parameter

src/ledger.js, src/trezor.js
The XFP is converted from an int to a hex string, but wasn't being zero-padded to 8 characters, so there was a 1-in-16 chance of a 7 character XFP, and a 1-in-256 chance of a 6-digit XFP.
This PR adds the necessary zero-padding.
=> XFP should be 8-char hex

src/ledger.js
Follow-up to #37 
Test suite wallet words with passphrase `y`
=> rootFingerprint is used twice, zero pad the base function

src/coldcard.fixtures.js, src/coldcard.js
Coldcard released firmware [version 3.2.1](https://github.com/Coldcard/firmware/tree/2021-01-07T1439-v3.2.1) today. It has several multisig updates.
Originally we left out the `Derivation` parameter in our wallet config files (even though we had (and still have) access to it via what comes in) because the Coldcard was only paying attention to the first entry for `Derivation`. And in an effort to alleviate confusion (and because it wasn't a required parameter at the time), we left it out completely and happily continued with `Derivation: Unknown`.
Xpub specific derivations are now supported and `Derivation: Unknown` is no longer supported. Added logic to mask out the derivation to the proper depth (included in the xpub itself) if we do not know the bip32path for a particular xpub in the …
=> Quickfix: update coldcard wallet config output to include bip32paths

fixtures/coldcard.fixtures.js, fixtures/custom.fixtures.js, package-lock.json, package.json, src/coldcard.test.js, src/custom.fixtures.js, src/custom.js, src/custom.test.js, src/index.js
We need to support custom flows for text-based xpub upload and custom PSBT signing, so I have created the interaction classes below to support these use cases.
Includes unit tests and fixture data.
I have also edited the exports and deciding device interaction class such that they're in alphabetic order. This will cause conflicts when merging into other existing PRs, but as we add more keystores, this will be a nice thing to keep in mind.
If we think it will cause too much hassle, lmk and I can remove it.
=> Adds "custom" text-based device and re-orders keystores alphabetically

package.json
In order for us to release any updates to Caravan, we need to peg the ledger-webusb npm package to `0.53.0` because they reverted that fix in `0.53.1` and it's just broken and they're waiting on Chromium to release.
Things work fine for us on this patched version, so let's stay here until after Chromium releases a patch or Ledger figures out another fix.
The lock file already has this version, so no changes expected there.
=> Peg Ledger WebUSB to version `5.53.0` until Chromium releases their patch

package-lock.json, package.json, src/coldcard.js, src/custom.js, src/custom.test.js, src/index.js, src/interaction.js, src/ledger.js, src/ledger.test.js, src/trezor.js, src/trezor.test.js
Utilizes new functionality in `unchained-bitcoin` to allow a Ledger to sign a PSBT, working in `P2SH` for now.
If the PSBT is defined when we call the interaction class, we will take the provided PSBT and translate it into
- inputs
- outputs
- bip32Paths
which can be sent to the Ledger for signing.
Again, if the PSBT is defined when we call the interaction class, once the signatures come back from the device, we will return a partially signed PSBT (with the signatures returned from the device inserted and validated) instead of the normal array of signatures.
=> Adds support for Ledger/Trezor PSBT signing for P2SH case

src/trezor.js, src/trezor.test.js
In https://github.com/unchained-capital/unchained-wallets/pull/61 - we removed the references to `parse` as they should not be on `DirectKeystoreInteraction`s ... forgot to replace the ones in Pubkey / Xpub Export -- this fixes that problem.
=> Bugfix - missed a function call replace in PR#61

package-lock.json, package.json, src/trezor.js, src/trezor.test.js
Quick POC of integrating Trezor Connect v9 beta.
v9 Docs: https://github.com/trezor/trezor-suite/tree/develop/packages/connect
=> chore(trezor): Upgrade Trezor Connect to v9

package-lock.json, src/index.js, src/ledger.test.ts, src/ledger.ts, src/policy.ts
Adds a new signing interaction for ledger v2. 
There is a standalone interaction and there is backwards compatibility built in to the existing interaction such that the new interaction will be used as a fallback.
These changes require the two dependent PRs in unchained-bitcoin to work: [PSBTv2Maps](https://github.com/unchained-capital/unchained-bitcoin/pull/62) and [this patch](https://github.com/Shadouts/unchained-bitcoin/pull/1).
New functionality can be tested out with [these updates](https://github.com/unchained-capital/caravan/pull/287) to the caravan test suite
=> Ledger v2 signing interactions

src/ledger.ts
OS: Linux
Browser: Chrome 110.0.0.0
unchained-wallets: v.0.1.27
Keystore: Ledger
`await transport.close()` fails with error `index.js:1 DOMException: Failed to execute 'releaseInterface' on 'USBDevice': Unable to release interface.` interrupting the completion of many tests. Catching it here (and logging it) allows for tests to complete.
=> fix: catch a failed transport.close()

src/index.ts
needed to fix a bug in caravan's test suite for comparing signatures.
=> fix: pass requestSignaturesArray option to signing interaction

package-lock.json, package.json, src/ledger.ts
PSBTv2 needed some fixes to handle P2WSH signing that were provided in an upgrade to unchained-bitcoin.
=> fix: upgrade uc-bitcoin for required psbtv2 fixes

src/index.ts, src/ledger.test.ts, src/ledger.ts, src/policy.test.ts, src/policy.ts
When working on confirm address on device in Caravan outside of the test suite context, I ran into issues where the API was a little clunky and didn't match with what was going on in the other keystore (trezor). This feels cleaner anyway. Ledger wants braid and address index, which is just available in bip32 path anyway. 
Companion draft PR up in Caravan that uses this functionality: https://github.com/unchained-capital/caravan/pull/296
=> feat(ledger): use bip32path for ledger confirm address api

src/policy.test.ts, src/policy.ts
ledger will throw an invalid data error if there is trailing whitespace. There's no need to allow this in the policy information anyway so removing when creating the policy for registration and other interactions should avoid this issue entirely.
=> Trim wallet name

README.md
This is a relatively small work around in order to get `npm link` to work with apps like Caravan. This isn't a long term solution as unchained-wallets should be upgraded to be an ESM module instead of a CJS module. Once the codebase is converted, `npm link` should be all that's needed.
=> fix: update readme with instructions on how to develop and use locally

src/ledger.ts, src/policy.test.ts, src/policy.ts
This should resolve an issue of immutability for wallet policy registrations with ledger where if a registration hmac is created with keys in one particular order and then that registration is attempted to be verified against a policy with the keys in a different order, then they won't match and the registration will fail to verify. 
This will be a minor version update since it could break any registrations that were handling the order consistently before passing it to uc-wallets and the order would be changed by the sorting here. 
I tested this in Caravan which you can see in the screenshots below. The first two are registering for the bob key without this change in the uc-wallets dependency and changing the order (which you can see in the key table) 
**First Alice (0) - Bob (1)**
**Then …
=> feat(policy): order key origins when instantiating wallet policy

src/ledger.ts, src/trezor.js, src/trezor.test.js
This was causing some issues in some build contexts. Given the new minimum nodejs requirement, this change should be fine. Confirmed that it compiles without errors as well.
=> fix: change old cjs require to esm imports

package-lock.json, package.json
This change upgrades packages for security and compatibility purposes. The upgrade to unchained-bitcoin is non-essential as its changes are unused by this lib, but it was a couple versions behind.
From npm v8.11.0 and node v16.16.0
```
$ npm audit fix
$ npm i unchained-bitcoin@0.6.0
```
=> fix: update packages audit and uc-bitcoin

src/trezor.js
This change affects Trezor and changes the default from assuming localhost to assuming whatever the browser host is. Not all development environments are configured to run services at the host machine level. Using browser host as the default will allow for a stateless default which does not have limitations of a localhost configuration. For example: There may be a development environment running remotely from the browser and port mapped to forward the trezor requests to its Trezor Connect dev service.
=> Trezor: Use browser host for dev URL defaults rather than assume localhost

src/trezor.js
This should allow unchained-wallets to continue allowing trezor connection in local development in an app running on vite using the vite prefix variation of CRA "react_app" env vars prefixes
=> fix: vite env vars for trezor

.github/workflows/release-please.yml
I think we were missing some things, probably because of some out of date/incomplete example readmes. Came up with this solution combining [this](https://github.com/google-github-actions/release-please-action#automating-publication-to-npm) and [this](https://github.com/marketplace/actions/release-please-action#outputs)
=> fix: actions yaml bugs

package-lock.json, package.json
Fixes an error where when ledger interactions were being instantiated they would fail when the Transport was being created with:
`Class constructor Transport cannot be invoked without 'new'`
It's unclear what specifically was broken but in comparing situations where the error was not showing, it seemed to be when @ledgerhq/hw-transport-webusb was using an older dependency of `@legerhq/hw-transport`, working on v6.28.1 but not on the newer v6.28.8
=> fix: lock ledger dependencies to avoid js errors

src/trezor.ts
A recent release of the trezor connect web app ([9.1.10](https://github.com/trezor/trezor-suite/blob/develop/packages/connect/CHANGELOG.md#9110)) introduced a breaking change to trezor interactions. In caravan this can be reproduced by running through a confirm address flow which returns the following:
```
Invalid parameter "bundle/0/multisig/signatures" (= undefined): Required property
```
This change makes sure that, unless told otherwise via env vars, TrezorConnect should use a pinned version of trezor connect web app. This is probably a good idea for the long term anyway since, as this incident indicates, a change to trezor connect can cause a breaking change to any dependency without the ability to opt-in or out. 
This change was tested with a local instance of Caravan and Confirm …
=> fix(trezor): pin connect url to stable version
